### PR TITLE
Change font of body text

### PR DESCRIPTION
**Pull request by danielbeardsley**
And increase line-spacing to improve read-ability.

After:
image

### CODE REVIEW

**Comment by adam000** [comment]
Looks good :+1:

**Comment by xiongchiamiov** [comment]
I took a look at [a page on iA](http://ia.net/blog/Improving-the-Digital-Reading-Experience/) immediately after looking at our blog, and it was immediately evident how bad our site looks - namely in regards to font size.  We're not the worst, but there's still too much squinting necessary.  So I decided to bump things up even more than Danny did to see what happened.

# Results

## Post

Currently deployed:
image

Danny's changes:
image

Plus my changes:
image

## Index

Currently deployed:
image

Danny's changes:
image

Plus my changes:
image

**Comment by adam000** [comment]
An even better improvement :+1:

**Comment by MutantFreak** [comment]
@xiongchiamiov Thank you, thank you, thank you. Every time I read anything on our blog it bothered my eyes squinting so much. No longer.

**Comment by danielbeardsley** [comment]
I'm OK with this after altering the gist font size.

**Pull request merged**
