### PR TITLE
Post: Designing user interfaces for your mother

### PR DESCRIPTION
**Pull request by xiongchiamiov**
A cross-post of Tony's pretty awesome article for The Next Web.

### CODE REVIEW

**Comment by xiongchiamiov** [comment]
Tony graciously gave me permission to cross-post this, so our dev blog isn't just a bunch of developers rambling on about technical this and technical that. :)

I didn't include the images from [the original article](http://thenextweb.com/dd/2013/08/12/designing-user-interfaces-for-your-mother/) because I wasn't sure if we had the rights to them.  I'm also not sure how they'd look in this site's design: I think we run a smaller article width.  It does make the whole thing a bit more drab, though.  Thoughts?

**Comment by xiongchiamiov** [comment]
Oh, guess I should ping @tgines .

**Comment by brotatos** [comment]
Cool post! CR :octopus:

**Comment by MutantFreak** [comment]
@xiongchiamiov Let's not wait to figure out image permissions. The article went out today, so let's get this out today as well.

**Comment by tgines** [comment]
Oh, they're my own images. We have rights to them.

**Pull request merged**
